# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://github.com/marketplace/actions/bazel-action

name: Solo Bazel Test (Ubuntu 22.04)

on: push

env:
  BAZEL_TARGET: ${{ github.event.inputs.target }}
  BAZEL_RUNS_PER_TEST: ${{ github.event.inputs.runs_per_test }}

jobs:
  build:
    name: Bazel Test (opt)
    runs-on:
      labels: ubuntu-22.04-64core
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2

      - name: Restore Nightly Bazel Cache
        uses: actions/cache/restore@v4
        with:
          path: "~/.cache/bazel"
          key: bazel-cache-nightly-${{ runner.os }}-${{ github.sha }}
          restore-keys: bazel-cache-nightly-${{ runner.os }}-

      - name: Install dependencies via apt
        run: sudo apt-get install python3-distutils python3-dev python-is-python3 libtinfo5  build-essential liblapack-dev libblas-dev gfortran

      - name: Bazel Test Target (opt)
        run: |
          bazel test -c opt --test_output=all --runs_per_test=$BAZEL_RUNS_PER_TEST -- $BAZEL_TARGET
